[workspace]

members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Aurélien Clu. <john@doe.johndoe>"]
description = "template-rust"
readme = "README.md"
edition = "2021"
license = "UNLICENSE"
